version: '3'
services:
  ambassador_backend:
    build: .
    image: antoniopapa/ambassador:0.0.1
    environment:
      DB_HOST:
      DB_PORT: 3306
      DB_DATABASE:
      DB_USERNAME:
      DB_PASSWORD:
      KAFKA_QUEUE:
      BOOTSTRAP_SERVERS:
      SECURITY_PROTOCOL: SASL_SSL
      SASL_USERNAME:
      SASL_PASSWORD:
      SASL_MECHANISMS: PLAIN
      GROUP_ID:
      USERS_MS: users-backend:8001
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: kafka
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 8003:8000
    command: >
      sh -c "php artisan config:cache
      && php artisan serve --host=0.0.0.0"

  ambassador_queue:
    build: .
    image: antoniopapa/ambassador:0.0.1
    environment:
      DB_HOST:
      DB_PORT: 3306
      DB_DATABASE:
      DB_USERNAME:
      DB_PASSWORD:
      KAFKA_QUEUE:
      BOOTSTRAP_SERVERS:
      SECURITY_PROTOCOL:
      SASL_USERNAME:
      SASL_PASSWORD:
      SASL_MECHANISMS: PLAIN
      GROUP_ID:
      USERS_MS: users-backend:8001
      CACHE_DRIVER: file
      QUEUE_CONNECTION: kafka
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: >
      sh -c "php artisan config:cache
      && php artisan queue:work"

  redis:
    image: redis
    ports:
      - 6379:6379
