apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: checkout-backend
  name: checkout-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: checkout-backend
  template:
    metadata:
      labels:
        io.kompose.service: checkout-backend
    spec:
      containers:
        - args:
            - php
            - artisan
            - config:cache;
            - php
            - artisan
            - serve
            - --host=0.0.0.0
          env:
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: BOOTSTRAP_SERVERS
            - name: CHECKOUT_URL
              value: http://localhost:5000
            - name: DB_DATABASE
              value: checkout
            - name: DB_HOST
              value:
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: GROUP_ID
              value: mygroup
            - name: KAFKA_QUEUE
              value: checkout_topic
            - name: QUEUE_CONNECTION
              value: kafka
            - name: SASL_MECHANISMS
              value: PLAIN
            - name: SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_PASSWORD
            - name: SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_USERNAME
            - name: SECURITY_PROTOCOL
              value: SASL_SSL
            - name: STRIPE_SECRET
              value:
            - name: USERS_MS
              value: users-backend:8001
          image: antoniopapa/checkout:0.0.1
          name: checkout-backend
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: checkout-backend
  name: checkout-backend
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8000
  selector:
    io.kompose.service: checkout-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: checkout-queue
  name: checkout-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: checkout-queue
  template:
    metadata:
      labels:
        io.kompose.service: checkout-queue
    spec:
      containers:
        - args:
            - php
            - artisan
            - config:cache;
            - php
            - artisan
            - serve
            - queue:work
          env:
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: BOOTSTRAP_SERVERS
            - name: DB_DATABASE
              value: checkout
            - name: DB_HOST
              value:
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: GROUP_ID
              value: mygroup
            - name: KAFKA_QUEUE
              value: checkout_topic
            - name: QUEUE_CONNECTION
              value: kafka
            - name: SASL_MECHANISMS
              value: PLAIN
            - name: SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_PASSWORD
            - name: SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_USERNAME
            - name: SECURITY_PROTOCOL
              value: SASL_SSL
            - name: USERS_MS
              value: users-backend:8001
          image: antoniopapa/checkout:0.0.1
          name: checkout-queue
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"

